### ISSUE TITLE
Question: Setting Background/Text shadow

### ISSUE THREAD

**Issue by LxkasDEV** [TheNextLvl-net/holograms#13]
Idk if i overlooked something but when creating a text-Hologram, you cant change the Background or the Text shadown or stuff like that because a Hologram is just a Display and not a TextDisplay. Is there any way arrount to change this stuff or will this be (or not) implemented?

**Comment by NonSwag** [comment]
Could you send me the code how you create the hologram?
If I remember correctly the create text hologram method provides a text display.

**Comment by NonSwag** [comment]
![image](https://github.com/user-attachments/assets/ec219640-4146-4502-8f9a-6f862ca703d6)

**Comment by NonSwag** [comment]
The `TextHologram` extends `TextDisplay`
`Hologram` only extends `Display`

Maybe you assigned `Hologram` instead of `TextHologram` to your variable?

![image](https://github.com/user-attachments/assets/ac172a6d-7611-4316-a302-f727ce38c8f6)

**Comment by LxkasDEV** [comment]
Yeah, my bad. thats exactly what happened. Thanks for the quick help!
